my_ramka/gallery/urls.py
from django.urls import path, include
from gallery import views

app_name = "gallery"

urlpatterns = [
    path('', views.IndexListView.as_view(), name="index"),
    path('create/', views.PostCreateView.as_view(), name="post"),
]

my_ramka/my_ramka/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth.forms import UserCreationForm
from users.forms import MyUserCreationForm
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("pages/", include("pages.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path(
        "auth/registration/",
        CreateView.as_view(
            template_name="registration/registration_form.html",
            form_class=MyUserCreationForm,
            success_url=reverse_lazy("gallery:index"),
        ),
        name="registration",
    ),
    path('', include('gallery.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_ramka/pages/urls.py
from django.urls import path
from django.views.generic import TemplateView

app_name = "pages"

urlpatterns = [
    path(
        "about/",
        TemplateView.as_view(
            template_name="pages/about.html"
        ),
        name="about"
    ),
]

my_ramka/gallery/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse


User = settings.AUTH_USER_MODEL
MAX_LENGTH_FIELD = 15
MAX_LENGTH_SUBSTRING = 35


class CreatedAtModel(models.Model):
    created_at = models.DateTimeField(
        auto_now_add=True,
        null=True,
        verbose_name="Добавлено",
    )

    class Meta:
        abstract = True


class IsPublishedModel(models.Model):
    is_published = models.BooleanField(
        default=True,
        verbose_name="Опубликовано",
        help_text="Снимите галочку, чтобы скрыть публикацию.",
    )

    class Meta:
        abstract = True


class Location(CreatedAtModel, IsPublishedModel):
    name = models.CharField(
        max_length=MAX_LENGTH_FIELD,
        verbose_name="Название места",
    )

    class Meta:
        verbose_name = "местоположение"
        verbose_name_plural = "Местоположения"

    def __str__(self):
        return self.name[:MAX_LENGTH_SUBSTRING]


class Category(CreatedAtModel):
    title = models.CharField(
        max_length=MAX_LENGTH_FIELD, verbose_name="Заголовок"
    )
    description = models.TextField(verbose_name="Описание")
    slug = models.SlugField(
        unique=True,
        verbose_name="Идентификатор",
        help_text=(
            "Идентификатор страницы для URL;"
            "разрешены символы латиницы, цифры, дефис и подчёркивание."
        )
    )

    class Meta:
        verbose_name = "категория"
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.title[:MAX_LENGTH_SUBSTRING]

    def get_absolute_url(self):
        return reverse("blog:category_posts", args=[self.slug])


class Post(CreatedAtModel, IsPublishedModel):
    title = models.CharField(
        max_length=MAX_LENGTH_FIELD,
        verbose_name="Заголовок",
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name="Автор публикации",
    )
    location = models.ForeignKey(
        Location,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        verbose_name="Местоположение",

    )
    category = models.ForeignKey(
        Category,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        verbose_name="Категория",

    )
    image = models.ImageField(
        "Фото", upload_to="posts_images", blank=True)

    class Meta:
        verbose_name = "публикация"
        verbose_name_plural = "Публикации"
        default_related_name = "posts"

    def __str__(self):
        return self.title[:MAX_LENGTH_SUBSTRING]

    # def get_absolute_url(self):
    #     return reverse("blog:post_detail", args=[self.pk])

my_ramka/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class MyUser(AbstractUser):
    bio = models.TextField('Биография', blank=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["username", "email"],
                name="unique_follow",
            ),
        ]

my_ramka/gallery/forms.py
from django import forms
from django.contrib.auth import get_user_model

from gallery.models import Post

User = get_user_model()


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ("author",)
        widgets = {
            "pub_date": forms.DateTimeInput(format='%Y-%m-%d %H:%M:%S',
                                            attrs={"type": "datetime-local"})
        }

my_ramka/users/forms.py
from typing import Any
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

User = get_user_model()


class MyUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("username", "email", )

    def clean(self) -> dict[str, Any]:
        if self.cleaned_data["email"] == self.cleaned_data["username"]:
            raise ValidationError("Email and username must be different")
        return super().clean()

my_ramka/gallery/views.py
from django.shortcuts import render
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView)
from gallery.models import Post
from gallery.forms import PostForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse, reverse_lazy


class IndexListView(ListView):
    model = Post
    template_name = "gallery/index.html"
    paginate_by = 10


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name = "gallery/post.html"

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self) -> str:
        return reverse_lazy("gallery:index")

my_ramka/templates/base.html
{% load static %}
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    {% comment %} <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image" /> {% endcomment %}
    {% comment %} <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}" /> {% endcomment %}
    {% comment %} <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}" />
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}" /> {% endcomment %}
    <title>
      {% block title %}

      {% endblock %}
    </title>
    {% bootstrap_css %}
  </head>
  <body>
    {% include 'includes/header.html' %}
    <main class="">
      <div class="container py-5 row row-cols-2 mx-auto">
        {% block content %}

        {% endblock %}
      </div>
    </main>
    {% comment %} {% include 'includes/footer.html' %} {% endcomment %}
  </body>
</html>

my_ramka/templates/gallery/index.html
{% extends 'base.html' %}
{% block title %}
  Галлерея
{% endblock %}
{% block content %}
  {% for post in page_obj %}
    <article class="mb-5">
      {% include 'includes/post_card.html' %}
    </article>
  {% endfor %}
  {% comment %} {% include 'includes/paginator.html' %} {% endcomment %}
{% endblock %}

my_ramka/templates/gallery/post.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block title %}
  {% if '/edit/' in request.path %}
    Редактирование публикации
  {% elif '/delete/' in request.path %}
    Удаление публикации
  {% else %}
    Добавление публикации
  {% endif %}
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
        {% if '/edit/' in request.path %}
          Редактирование публикации
        {% elif '/delete/' in request.path %}
          Удаление публикации
        {% else %}
          Добавление публикации
        {% endif %}
      </div>
      <div class="card-body">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% if not '/delete/' in request.path %}
            {% bootstrap_form form %}
          {% else %}
            <article>
              {% if form.instance.image %}
                <a href="{{ form.instance.image.url }}" target="_blank"><img class="border-3 rounded img-fluid img-thumbnail mb-2" src="{{ form.instance.image.url }}" /></a>
              {% endif %}
              {% if form.instance.location and form.instance.location.is_published %}
                {{ form.instance.location.name }}
              {% else %}
                Планета Земля
              {% endif %}<br />
              <h3>{{ form.instance.title }}</h3>
              <p>{{ form.instance.text|linebreaksbr }}</p>
            </article>
          {% endif %}
          {% bootstrap_button button_type='submit' content='Отправить' %}
        </form>
      </div>
    </div>
  </div>
{% endblock %}

my_ramka/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'gallery:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        Рамка
      </a>
      {% with request.resolver_match.view_name as view_name %}
        <ul class="nav nav-pills">
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'pages:about' %} text-white {% endif %}" href="{% url 'pages:about' %}">
              О проекте
            </a>
          </li>
          {% if user.is_authenticated %}
            <div class="btn-group" role="group" aria-label="Basic outlined example">
              <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
                  href="{% url 'gallery:post' %}">Написать пост</a></button>
              <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
                  {% comment %} href="{% url 'blog:profile' user.username %}">{{ user.username }}</a></button> {% endcomment %}
              <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
                  href="{% url 'logout' %}">Выйти</a></button>
            </div>
          {% else %}
            <div class="btn-group" role="group" aria-label="Basic outlined example">
              <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
                  href="{% url 'login' %}">Войти</a></button>
              <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
                  href="{% url 'registration' %}">Регистрация</a></button>
            </div>
          {% endif %}
        </ul>
      {% endwith %}
    </div>
  </nav>
</header>

my_ramka/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            << </a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            >>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            Последняя
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

my_ramka/templates/includes/post_card.html
<div class="d-flex justify-content-center" >
  <div class="card">
    <div class="card-body">
      {% if post.image %}
        <a href="{{ post.image.url }}" target="_blank"><img class="border-3 rounded img-fluid img-thumbnail mb-2 mx-auto d-block" src="{{ post.image.url }}" /></a>
      {% endif %}
      <h5 class="card-title">{{ post.title }}</h5>
      <h6 class="card-subtitle mb-2 text-muted">
        {% comment %} <small>
          {% if not post.is_published %}
            <p class="text-danger">Пост снят с публикации админом</p>
          {% elif not post.category.is_published %}
            <p class="text-danger">Выбранная категория снята с публикации админом</p>
          {% endif %} {% endcomment %}
          {% comment %} {{ post.pub_date|date:'d E Y, H:i' }} |{% if post.location and post.location.is_published %}
            {{ post.location.name }}
          {% else %}
            Планета Земля
          {% endif %}<br />
          От автора <a class="text-muted" href="{% url 'blog:profile' post.author.username %}">@{{ post.author.username }}</a> в категории{% include 'includes/category_link.html' %} {% endcomment %}
          {% comment %}
        </small> {% endcomment %}
      </h6>
      <p class="card-text">{{ post.text|truncatewords:10 }}</p>
      {% comment %} <a href="{% url 'blog:post_detail' post.id %}" class="card-link">Читать полный текст</a>
      <a href="{% url 'blog:post_detail' post.id %}" class="card-link text-muted">Комментарии ({{ post.comment_count }})</a> {% endcomment %}
    </div>
  </div>
</div>

my_ramka/templates/pages/about.html
{% extends "base.html" %}
{% block title %}
  О проекте
{% endblock %}
{% block content %}
  <div class="d-flex justify-content-center">
    <div class="card" style="width: 80%;">
      <div class="card-header">
        О проекте
      </div>
      <div class="card-body">
        <p>
            Галерея картинок "Рамка"
        </p>
      </div>
    </div>
  </div>
{% endblock %}